#!/usr/bin/env bash

# bash is quite literally the worst.
# https://stackoverflow.com/a/179231/1438908
pushd . > '/dev/null';
SCRIPT_PATH="${BASH_SOURCE[0]:-$0}";
while [ -h "$SCRIPT_PATH" ];
do
  cd "$( dirname -- "$SCRIPT_PATH"; )";
  SCRIPT_PATH="$( readlink -f -- "$SCRIPT_PATH"; )";
done
cd "$( dirname -- "$SCRIPT_PATH"; )" > '/dev/null';
SCRIPT_PATH="$( pwd; )";
popd  > '/dev/null';

deno run --unstable -A "$SCRIPT_PATH/src/bin.ts" --log-level info "$@"
