# @info
# main & pull_request jobs cannot de-dupe their workflow configuration :(
# https://github.community/t5/GitHub-Actions/Start-a-workflow-from-another-workflow/td-p/37586
name: next
on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
      - name: checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # https://github.com/denolib/setup-deno
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.26.1
      - name: check
        run: ./rad check
      - name: site
        run: ./rad -l info site

      # release
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm init -y \
            && \
          npm install -D \
            "@semantic-release/commit-analyzer" \
            "@semantic-release/release-notes-generator" \
            "@semantic-release/github" \
            "@semantic-release/git" \
            "@semantic-release/exec" \
            && \
          npx semantic-release --dry-run
